include("$(MPY_DIR)/extmod/uasyncio/manifest.py")
freeze("$(MPY_DIR)/drivers/dht", "dht.py")
freeze("$(MPY_DIR)/drivers/display", ("lcd160cr.py", "lcd160cr_test.py"))
freeze("$(MPY_DIR)/drivers/onewire", "onewire.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/xpt2046.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/display.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/display_test.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/umatrix.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/simple3dcube.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/glcdfont.py")
freeze("$(BOARD_DIR)/frozen", "mcudev/fsmc.py")
